const ADD_TO_CART = "ADD_TO_CART";
const REMOVE_ITEM_FROM_CART = "REMOVE_ITEM_FROM_CART";
const INCREASE_QUANTITY = "INCREASE_QUANTITY";
const DECREASE_QUANTITY = "DECREASE_QUANTITY";
const CALCULATE_TOTAL = "CALCULATE_TOTAL";

export {
  ADD_TO_CART,
  REMOVE_ITEM_FROM_CART,
  INCREASE_QUANTITY,
  DECREASE_QUANTITY,
  CALCULATE_TOTAL,
};
